//Generated by wsdl2apex

public class CountryWebService {
    public class tContinent {
        public String sCode;
        public String sName;
        private String[] sCode_type_info = new String[]{'sCode','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] sName_type_info = new String[]{'sName','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'sCode','sName'};
    }
    public class tCurrency {
        public String sISOCode;
        public String sName;
        private String[] sISOCode_type_info = new String[]{'sISOCode','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] sName_type_info = new String[]{'sName','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'sISOCode','sName'};
    }
    public class CapitalCity_element {
        public String sCountryISOCode;
        private String[] sCountryISOCode_type_info = new String[]{'sCountryISOCode','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'sCountryISOCode'};
    }
    public class CurrencyNameResponse_element {
        public String CurrencyNameResult;
        private String[] CurrencyNameResult_type_info = new String[]{'CurrencyNameResult','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'CurrencyNameResult'};
    }
    public class CountryISOCodeResponse_element {
        public String CountryISOCodeResult;
        private String[] CountryISOCodeResult_type_info = new String[]{'CountryISOCodeResult','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'CountryISOCodeResult'};
    }
    public class CountriesUsingCurrencyResponse_element {
        public CountryWebService.ArrayOftCountryCodeAndName CountriesUsingCurrencyResult;
        private String[] CountriesUsingCurrencyResult_type_info = new String[]{'CountriesUsingCurrencyResult','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'CountriesUsingCurrencyResult'};
    }
    public class tCountryCodeAndName {
        public String sISOCode;
        public String sName;
        private String[] sISOCode_type_info = new String[]{'sISOCode','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] sName_type_info = new String[]{'sName','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'sISOCode','sName'};
    }
    public class ListOfLanguagesByName_element {
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class CountryName_element {
        public String sCountryISOCode;
        private String[] sCountryISOCode_type_info = new String[]{'sCountryISOCode','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'sCountryISOCode'};
    }
    public class CountryCurrency_element {
        public String sCountryISOCode;
        private String[] sCountryISOCode_type_info = new String[]{'sCountryISOCode','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'sCountryISOCode'};
    }
    public class CountryISOCode_element {
        public String sCountryName;
        private String[] sCountryName_type_info = new String[]{'sCountryName','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'sCountryName'};
    }
    public class CountryFlag_element {
        public String sCountryISOCode;
        private String[] sCountryISOCode_type_info = new String[]{'sCountryISOCode','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'sCountryISOCode'};
    }
    public class FullCountryInfoAllCountries_element {
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class CountryFlagResponse_element {
        public String CountryFlagResult;
        private String[] CountryFlagResult_type_info = new String[]{'CountryFlagResult','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'CountryFlagResult'};
    }
    public class ArrayOftCountryInfo {
        public CountryWebService.tCountryInfo[] tCountryInfo;
        private String[] tCountryInfo_type_info = new String[]{'tCountryInfo','http://www.oorsprong.org/websamples.countryinfo',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'tCountryInfo'};
    }
    public class CountryIntPhoneCode_element {
        public String sCountryISOCode;
        private String[] sCountryISOCode_type_info = new String[]{'sCountryISOCode','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'sCountryISOCode'};
    }
    public class CountryIntPhoneCodeResponse_element {
        public String CountryIntPhoneCodeResult;
        private String[] CountryIntPhoneCodeResult_type_info = new String[]{'CountryIntPhoneCodeResult','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'CountryIntPhoneCodeResult'};
    }
    public class ListOfCountryNamesGroupedByContinent_element {
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class ListOfCurrenciesByCode_element {
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class ArrayOftCurrency {
        public CountryWebService.tCurrency[] tCurrency;
        private String[] tCurrency_type_info = new String[]{'tCurrency','http://www.oorsprong.org/websamples.countryinfo',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'tCurrency'};
    }
    public class tCountryInfo {
        public String sISOCode;
        public String sName;
        public String sCapitalCity;
        public String sPhoneCode;
        public String sContinentCode;
        public String sCurrencyISOCode;
        public String sCountryFlag;
        public CountryWebService.ArrayOftLanguage Languages;
        private String[] sISOCode_type_info = new String[]{'sISOCode','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] sName_type_info = new String[]{'sName','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] sCapitalCity_type_info = new String[]{'sCapitalCity','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] sPhoneCode_type_info = new String[]{'sPhoneCode','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] sContinentCode_type_info = new String[]{'sContinentCode','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] sCurrencyISOCode_type_info = new String[]{'sCurrencyISOCode','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] sCountryFlag_type_info = new String[]{'sCountryFlag','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] Languages_type_info = new String[]{'Languages','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'sISOCode','sName','sCapitalCity','sPhoneCode','sContinentCode','sCurrencyISOCode','sCountryFlag','Languages'};
    }
    public class CountryCurrencyResponse_element {
        public CountryWebService.tCurrency CountryCurrencyResult;
        private String[] CountryCurrencyResult_type_info = new String[]{'CountryCurrencyResult','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'CountryCurrencyResult'};
    }
    public class ListOfCountryNamesByNameResponse_element {
        public CountryWebService.ArrayOftCountryCodeAndName ListOfCountryNamesByNameResult;
        private String[] ListOfCountryNamesByNameResult_type_info = new String[]{'ListOfCountryNamesByNameResult','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'ListOfCountryNamesByNameResult'};
    }
    public class ListOfLanguagesByCode_element {
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class ListOfContinentsByName_element {
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class LanguageName_element {
        public String sISOCode;
        private String[] sISOCode_type_info = new String[]{'sISOCode','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'sISOCode'};
    }
    public class CountryNameResponse_element {
        public String CountryNameResult;
        private String[] CountryNameResult_type_info = new String[]{'CountryNameResult','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'CountryNameResult'};
    }
    public class ListOfCurrenciesByNameResponse_element {
        public CountryWebService.ArrayOftCurrency ListOfCurrenciesByNameResult;
        private String[] ListOfCurrenciesByNameResult_type_info = new String[]{'ListOfCurrenciesByNameResult','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'ListOfCurrenciesByNameResult'};
    }
    public class tLanguage {
        public String sISOCode;
        public String sName;
        private String[] sISOCode_type_info = new String[]{'sISOCode','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] sName_type_info = new String[]{'sName','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'sISOCode','sName'};
    }
    public class CurrencyName_element {
        public String sCurrencyISOCode;
        private String[] sCurrencyISOCode_type_info = new String[]{'sCurrencyISOCode','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'sCurrencyISOCode'};
    }
    public class FullCountryInfoResponse_element {
        public CountryWebService.tCountryInfo FullCountryInfoResult;
        private String[] FullCountryInfoResult_type_info = new String[]{'FullCountryInfoResult','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'FullCountryInfoResult'};
    }
    public class CountriesUsingCurrency_element {
        public String sISOCurrencyCode;
        private String[] sISOCurrencyCode_type_info = new String[]{'sISOCurrencyCode','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'sISOCurrencyCode'};
    }
    public class LanguageISOCodeResponse_element {
        public String LanguageISOCodeResult;
        private String[] LanguageISOCodeResult_type_info = new String[]{'LanguageISOCodeResult','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'LanguageISOCodeResult'};
    }
    public class ListOfContinentsByCodeResponse_element {
        public CountryWebService.ArrayOftContinent ListOfContinentsByCodeResult;
        private String[] ListOfContinentsByCodeResult_type_info = new String[]{'ListOfContinentsByCodeResult','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'ListOfContinentsByCodeResult'};
    }
    public class LanguageISOCode_element {
        public String sLanguageName;
        private String[] sLanguageName_type_info = new String[]{'sLanguageName','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'sLanguageName'};
    }
    public class ListOfContinentsByCode_element {
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class ListOfCountryNamesByCodeResponse_element {
        public CountryWebService.ArrayOftCountryCodeAndName ListOfCountryNamesByCodeResult;
        private String[] ListOfCountryNamesByCodeResult_type_info = new String[]{'ListOfCountryNamesByCodeResult','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'ListOfCountryNamesByCodeResult'};
    }
    public class ArrayOftLanguage {
        public CountryWebService.tLanguage[] tLanguage;
        private String[] tLanguage_type_info = new String[]{'tLanguage','http://www.oorsprong.org/websamples.countryinfo',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'tLanguage'};
    }
    public class ListOfCountryNamesByCode_element {
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class FullCountryInfoAllCountriesResponse_element {
        public CountryWebService.ArrayOftCountryInfo FullCountryInfoAllCountriesResult;
        private String[] FullCountryInfoAllCountriesResult_type_info = new String[]{'FullCountryInfoAllCountriesResult','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'FullCountryInfoAllCountriesResult'};
    }
    public class ListOfCountryNamesGroupedByContinentResponse_element {
        public CountryWebService.ArrayOftCountryCodeAndNameGroupedByContinent ListOfCountryNamesGroupedByContinentResult;
        private String[] ListOfCountryNamesGroupedByContinentResult_type_info = new String[]{'ListOfCountryNamesGroupedByContinentResult','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'ListOfCountryNamesGroupedByContinentResult'};
    }
    public class ArrayOftCountryCodeAndNameGroupedByContinent {
        public CountryWebService.tCountryCodeAndNameGroupedByContinent[] tCountryCodeAndNameGroupedByContinent;
        private String[] tCountryCodeAndNameGroupedByContinent_type_info = new String[]{'tCountryCodeAndNameGroupedByContinent','http://www.oorsprong.org/websamples.countryinfo',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'tCountryCodeAndNameGroupedByContinent'};
    }
    public class FullCountryInfo_element {
        public String sCountryISOCode;
        private String[] sCountryISOCode_type_info = new String[]{'sCountryISOCode','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'sCountryISOCode'};
    }
    public class tCountryCodeAndNameGroupedByContinent {
        public CountryWebService.tContinent Continent;
        public CountryWebService.ArrayOftCountryCodeAndName CountryCodeAndNames;
        private String[] Continent_type_info = new String[]{'Continent','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] CountryCodeAndNames_type_info = new String[]{'CountryCodeAndNames','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'Continent','CountryCodeAndNames'};
    }
    public class ListOfCurrenciesByCodeResponse_element {
        public CountryWebService.ArrayOftCurrency ListOfCurrenciesByCodeResult;
        private String[] ListOfCurrenciesByCodeResult_type_info = new String[]{'ListOfCurrenciesByCodeResult','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'ListOfCurrenciesByCodeResult'};
    }
    public class ListOfLanguagesByNameResponse_element {
        public CountryWebService.ArrayOftLanguage ListOfLanguagesByNameResult;
        private String[] ListOfLanguagesByNameResult_type_info = new String[]{'ListOfLanguagesByNameResult','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'ListOfLanguagesByNameResult'};
    }
    public class ListOfContinentsByNameResponse_element {
        public CountryWebService.ArrayOftContinent ListOfContinentsByNameResult;
        private String[] ListOfContinentsByNameResult_type_info = new String[]{'ListOfContinentsByNameResult','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'ListOfContinentsByNameResult'};
    }
    public class CapitalCityResponse_element {
        public String CapitalCityResult;
        private String[] CapitalCityResult_type_info = new String[]{'CapitalCityResult','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'CapitalCityResult'};
    }
    public class ListOfCountryNamesByName_element {
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class ArrayOftContinent {
        public CountryWebService.tContinent[] tContinent;
        private String[] tContinent_type_info = new String[]{'tContinent','http://www.oorsprong.org/websamples.countryinfo',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'tContinent'};
    }
    public class ArrayOftCountryCodeAndName {
        public CountryWebService.tCountryCodeAndName[] tCountryCodeAndName;
        private String[] tCountryCodeAndName_type_info = new String[]{'tCountryCodeAndName','http://www.oorsprong.org/websamples.countryinfo',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'tCountryCodeAndName'};
    }
    public class ListOfCurrenciesByName_element {
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class ListOfLanguagesByCodeResponse_element {
        public CountryWebService.ArrayOftLanguage ListOfLanguagesByCodeResult;
        private String[] ListOfLanguagesByCodeResult_type_info = new String[]{'ListOfLanguagesByCodeResult','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'ListOfLanguagesByCodeResult'};
    }
    public class LanguageNameResponse_element {
        public String LanguageNameResult;
        private String[] LanguageNameResult_type_info = new String[]{'LanguageNameResult','http://www.oorsprong.org/websamples.countryinfo',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo','true','false'};
        private String[] field_order_type_info = new String[]{'LanguageNameResult'};
    }
    public class CountryInfoServiceSoap {
        public String endpoint_x = 'http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso';
        public Map<String,String> inputHttpHeaders_x;
        public Map<String,String> outputHttpHeaders_x;
        public String clientCertName_x;
        public String clientCert_x;
        public String clientCertPasswd_x;
        public Integer timeout_x;
        private String[] ns_map_type_info = new String[]{'http://www.oorsprong.org/websamples.countryinfo', 'CountryWebService'};
        public CountryWebService.tCountryInfo FullCountryInfo(String sCountryISOCode) {
            CountryWebService.FullCountryInfo_element request_x = new CountryWebService.FullCountryInfo_element();
            request_x.sCountryISOCode = sCountryISOCode;
            CountryWebService.FullCountryInfoResponse_element response_x;
            Map<String, CountryWebService.FullCountryInfoResponse_element> response_map_x = new Map<String, CountryWebService.FullCountryInfoResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://www.oorsprong.org/websamples.countryinfo',
              'FullCountryInfo',
              'http://www.oorsprong.org/websamples.countryinfo',
              'FullCountryInfoResponse',
              'CountryWebService.FullCountryInfoResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.FullCountryInfoResult;
        }
        public String CountryFlag(String sCountryISOCode) {
            CountryWebService.CountryFlag_element request_x = new CountryWebService.CountryFlag_element();
            request_x.sCountryISOCode = sCountryISOCode;
            CountryWebService.CountryFlagResponse_element response_x;
            Map<String, CountryWebService.CountryFlagResponse_element> response_map_x = new Map<String, CountryWebService.CountryFlagResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://www.oorsprong.org/websamples.countryinfo',
              'CountryFlag',
              'http://www.oorsprong.org/websamples.countryinfo',
              'CountryFlagResponse',
              'CountryWebService.CountryFlagResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.CountryFlagResult;
        }
        public String CountryName(String sCountryISOCode) {
            CountryWebService.CountryName_element request_x = new CountryWebService.CountryName_element();
            request_x.sCountryISOCode = sCountryISOCode;
            CountryWebService.CountryNameResponse_element response_x;
            Map<String, CountryWebService.CountryNameResponse_element> response_map_x = new Map<String, CountryWebService.CountryNameResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://www.oorsprong.org/websamples.countryinfo',
              'CountryName',
              'http://www.oorsprong.org/websamples.countryinfo',
              'CountryNameResponse',
              'CountryWebService.CountryNameResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.CountryNameResult;
        }
        public CountryWebService.tCurrency CountryCurrency(String sCountryISOCode) {
            CountryWebService.CountryCurrency_element request_x = new CountryWebService.CountryCurrency_element();
            request_x.sCountryISOCode = sCountryISOCode;
            CountryWebService.CountryCurrencyResponse_element response_x;
            Map<String, CountryWebService.CountryCurrencyResponse_element> response_map_x = new Map<String, CountryWebService.CountryCurrencyResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://www.oorsprong.org/websamples.countryinfo',
              'CountryCurrency',
              'http://www.oorsprong.org/websamples.countryinfo',
              'CountryCurrencyResponse',
              'CountryWebService.CountryCurrencyResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.CountryCurrencyResult;
        }
        public CountryWebService.ArrayOftCurrency ListOfCurrenciesByName() {
            CountryWebService.ListOfCurrenciesByName_element request_x = new CountryWebService.ListOfCurrenciesByName_element();
            CountryWebService.ListOfCurrenciesByNameResponse_element response_x;
            Map<String, CountryWebService.ListOfCurrenciesByNameResponse_element> response_map_x = new Map<String, CountryWebService.ListOfCurrenciesByNameResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://www.oorsprong.org/websamples.countryinfo',
              'ListOfCurrenciesByName',
              'http://www.oorsprong.org/websamples.countryinfo',
              'ListOfCurrenciesByNameResponse',
              'CountryWebService.ListOfCurrenciesByNameResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.ListOfCurrenciesByNameResult;
        }
        public CountryWebService.ArrayOftCountryCodeAndName ListOfCountryNamesByCode() {
            CountryWebService.ListOfCountryNamesByCode_element request_x = new CountryWebService.ListOfCountryNamesByCode_element();
            CountryWebService.ListOfCountryNamesByCodeResponse_element response_x;
            Map<String, CountryWebService.ListOfCountryNamesByCodeResponse_element> response_map_x = new Map<String, CountryWebService.ListOfCountryNamesByCodeResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://www.oorsprong.org/websamples.countryinfo',
              'ListOfCountryNamesByCode',
              'http://www.oorsprong.org/websamples.countryinfo',
              'ListOfCountryNamesByCodeResponse',
              'CountryWebService.ListOfCountryNamesByCodeResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.ListOfCountryNamesByCodeResult;
        }
        public String CountryIntPhoneCode(String sCountryISOCode) {
            CountryWebService.CountryIntPhoneCode_element request_x = new CountryWebService.CountryIntPhoneCode_element();
            request_x.sCountryISOCode = sCountryISOCode;
            CountryWebService.CountryIntPhoneCodeResponse_element response_x;
            Map<String, CountryWebService.CountryIntPhoneCodeResponse_element> response_map_x = new Map<String, CountryWebService.CountryIntPhoneCodeResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://www.oorsprong.org/websamples.countryinfo',
              'CountryIntPhoneCode',
              'http://www.oorsprong.org/websamples.countryinfo',
              'CountryIntPhoneCodeResponse',
              'CountryWebService.CountryIntPhoneCodeResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.CountryIntPhoneCodeResult;
        }
        public String CurrencyName(String sCurrencyISOCode) {
            CountryWebService.CurrencyName_element request_x = new CountryWebService.CurrencyName_element();
            request_x.sCurrencyISOCode = sCurrencyISOCode;
            CountryWebService.CurrencyNameResponse_element response_x;
            Map<String, CountryWebService.CurrencyNameResponse_element> response_map_x = new Map<String, CountryWebService.CurrencyNameResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://www.oorsprong.org/websamples.countryinfo',
              'CurrencyName',
              'http://www.oorsprong.org/websamples.countryinfo',
              'CurrencyNameResponse',
              'CountryWebService.CurrencyNameResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.CurrencyNameResult;
        }
        public CountryWebService.ArrayOftCurrency ListOfCurrenciesByCode() {
            CountryWebService.ListOfCurrenciesByCode_element request_x = new CountryWebService.ListOfCurrenciesByCode_element();
            CountryWebService.ListOfCurrenciesByCodeResponse_element response_x;
            Map<String, CountryWebService.ListOfCurrenciesByCodeResponse_element> response_map_x = new Map<String, CountryWebService.ListOfCurrenciesByCodeResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://www.oorsprong.org/websamples.countryinfo',
              'ListOfCurrenciesByCode',
              'http://www.oorsprong.org/websamples.countryinfo',
              'ListOfCurrenciesByCodeResponse',
              'CountryWebService.ListOfCurrenciesByCodeResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.ListOfCurrenciesByCodeResult;
        }
        public CountryWebService.ArrayOftLanguage ListOfLanguagesByCode() {
            CountryWebService.ListOfLanguagesByCode_element request_x = new CountryWebService.ListOfLanguagesByCode_element();
            CountryWebService.ListOfLanguagesByCodeResponse_element response_x;
            Map<String, CountryWebService.ListOfLanguagesByCodeResponse_element> response_map_x = new Map<String, CountryWebService.ListOfLanguagesByCodeResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://www.oorsprong.org/websamples.countryinfo',
              'ListOfLanguagesByCode',
              'http://www.oorsprong.org/websamples.countryinfo',
              'ListOfLanguagesByCodeResponse',
              'CountryWebService.ListOfLanguagesByCodeResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.ListOfLanguagesByCodeResult;
        }
        public String LanguageISOCode(String sLanguageName) {
            CountryWebService.LanguageISOCode_element request_x = new CountryWebService.LanguageISOCode_element();
            request_x.sLanguageName = sLanguageName;
            CountryWebService.LanguageISOCodeResponse_element response_x;
            Map<String, CountryWebService.LanguageISOCodeResponse_element> response_map_x = new Map<String, CountryWebService.LanguageISOCodeResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://www.oorsprong.org/websamples.countryinfo',
              'LanguageISOCode',
              'http://www.oorsprong.org/websamples.countryinfo',
              'LanguageISOCodeResponse',
              'CountryWebService.LanguageISOCodeResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.LanguageISOCodeResult;
        }
        public String CapitalCity(String sCountryISOCode) {
            CountryWebService.CapitalCity_element request_x = new CountryWebService.CapitalCity_element();
            request_x.sCountryISOCode = sCountryISOCode;
            CountryWebService.CapitalCityResponse_element response_x;
            Map<String, CountryWebService.CapitalCityResponse_element> response_map_x = new Map<String, CountryWebService.CapitalCityResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://www.oorsprong.org/websamples.countryinfo',
              'CapitalCity',
              'http://www.oorsprong.org/websamples.countryinfo',
              'CapitalCityResponse',
              'CountryWebService.CapitalCityResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.CapitalCityResult;
        }
        public CountryWebService.ArrayOftLanguage ListOfLanguagesByName() {
            CountryWebService.ListOfLanguagesByName_element request_x = new CountryWebService.ListOfLanguagesByName_element();
            CountryWebService.ListOfLanguagesByNameResponse_element response_x;
            Map<String, CountryWebService.ListOfLanguagesByNameResponse_element> response_map_x = new Map<String, CountryWebService.ListOfLanguagesByNameResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://www.oorsprong.org/websamples.countryinfo',
              'ListOfLanguagesByName',
              'http://www.oorsprong.org/websamples.countryinfo',
              'ListOfLanguagesByNameResponse',
              'CountryWebService.ListOfLanguagesByNameResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.ListOfLanguagesByNameResult;
        }
        public CountryWebService.ArrayOftCountryCodeAndNameGroupedByContinent ListOfCountryNamesGroupedByContinent() {
            CountryWebService.ListOfCountryNamesGroupedByContinent_element request_x = new CountryWebService.ListOfCountryNamesGroupedByContinent_element();
            CountryWebService.ListOfCountryNamesGroupedByContinentResponse_element response_x;
            Map<String, CountryWebService.ListOfCountryNamesGroupedByContinentResponse_element> response_map_x = new Map<String, CountryWebService.ListOfCountryNamesGroupedByContinentResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://www.oorsprong.org/websamples.countryinfo',
              'ListOfCountryNamesGroupedByContinent',
              'http://www.oorsprong.org/websamples.countryinfo',
              'ListOfCountryNamesGroupedByContinentResponse',
              'CountryWebService.ListOfCountryNamesGroupedByContinentResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.ListOfCountryNamesGroupedByContinentResult;
        }
        public CountryWebService.ArrayOftCountryCodeAndName ListOfCountryNamesByName() {
            CountryWebService.ListOfCountryNamesByName_element request_x = new CountryWebService.ListOfCountryNamesByName_element();
            CountryWebService.ListOfCountryNamesByNameResponse_element response_x;
            Map<String, CountryWebService.ListOfCountryNamesByNameResponse_element> response_map_x = new Map<String, CountryWebService.ListOfCountryNamesByNameResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://www.oorsprong.org/websamples.countryinfo',
              'ListOfCountryNamesByName',
              'http://www.oorsprong.org/websamples.countryinfo',
              'ListOfCountryNamesByNameResponse',
              'CountryWebService.ListOfCountryNamesByNameResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.ListOfCountryNamesByNameResult;
        }
        public CountryWebService.ArrayOftContinent ListOfContinentsByName() {
            CountryWebService.ListOfContinentsByName_element request_x = new CountryWebService.ListOfContinentsByName_element();
            CountryWebService.ListOfContinentsByNameResponse_element response_x;
            Map<String, CountryWebService.ListOfContinentsByNameResponse_element> response_map_x = new Map<String, CountryWebService.ListOfContinentsByNameResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://www.oorsprong.org/websamples.countryinfo',
              'ListOfContinentsByName',
              'http://www.oorsprong.org/websamples.countryinfo',
              'ListOfContinentsByNameResponse',
              'CountryWebService.ListOfContinentsByNameResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.ListOfContinentsByNameResult;
        }
        public String LanguageName(String sISOCode) {
            CountryWebService.LanguageName_element request_x = new CountryWebService.LanguageName_element();
            request_x.sISOCode = sISOCode;
            CountryWebService.LanguageNameResponse_element response_x;
            Map<String, CountryWebService.LanguageNameResponse_element> response_map_x = new Map<String, CountryWebService.LanguageNameResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://www.oorsprong.org/websamples.countryinfo',
              'LanguageName',
              'http://www.oorsprong.org/websamples.countryinfo',
              'LanguageNameResponse',
              'CountryWebService.LanguageNameResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.LanguageNameResult;
        }
        public CountryWebService.ArrayOftContinent ListOfContinentsByCode() {
            CountryWebService.ListOfContinentsByCode_element request_x = new CountryWebService.ListOfContinentsByCode_element();
            CountryWebService.ListOfContinentsByCodeResponse_element response_x;
            Map<String, CountryWebService.ListOfContinentsByCodeResponse_element> response_map_x = new Map<String, CountryWebService.ListOfContinentsByCodeResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://www.oorsprong.org/websamples.countryinfo',
              'ListOfContinentsByCode',
              'http://www.oorsprong.org/websamples.countryinfo',
              'ListOfContinentsByCodeResponse',
              'CountryWebService.ListOfContinentsByCodeResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.ListOfContinentsByCodeResult;
        }
        public CountryWebService.ArrayOftCountryCodeAndName CountriesUsingCurrency(String sISOCurrencyCode) {
            CountryWebService.CountriesUsingCurrency_element request_x = new CountryWebService.CountriesUsingCurrency_element();
            request_x.sISOCurrencyCode = sISOCurrencyCode;
            CountryWebService.CountriesUsingCurrencyResponse_element response_x;
            Map<String, CountryWebService.CountriesUsingCurrencyResponse_element> response_map_x = new Map<String, CountryWebService.CountriesUsingCurrencyResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://www.oorsprong.org/websamples.countryinfo',
              'CountriesUsingCurrency',
              'http://www.oorsprong.org/websamples.countryinfo',
              'CountriesUsingCurrencyResponse',
              'CountryWebService.CountriesUsingCurrencyResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.CountriesUsingCurrencyResult;
        }
        public String CountryISOCode(String sCountryName) {
            CountryWebService.CountryISOCode_element request_x = new CountryWebService.CountryISOCode_element();
            request_x.sCountryName = sCountryName;
            CountryWebService.CountryISOCodeResponse_element response_x;
            Map<String, CountryWebService.CountryISOCodeResponse_element> response_map_x = new Map<String, CountryWebService.CountryISOCodeResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://www.oorsprong.org/websamples.countryinfo',
              'CountryISOCode',
              'http://www.oorsprong.org/websamples.countryinfo',
              'CountryISOCodeResponse',
              'CountryWebService.CountryISOCodeResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.CountryISOCodeResult;
        }
        public CountryWebService.ArrayOftCountryInfo FullCountryInfoAllCountries() {
            CountryWebService.FullCountryInfoAllCountries_element request_x = new CountryWebService.FullCountryInfoAllCountries_element();
            CountryWebService.FullCountryInfoAllCountriesResponse_element response_x;
            Map<String, CountryWebService.FullCountryInfoAllCountriesResponse_element> response_map_x = new Map<String, CountryWebService.FullCountryInfoAllCountriesResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://www.oorsprong.org/websamples.countryinfo',
              'FullCountryInfoAllCountries',
              'http://www.oorsprong.org/websamples.countryinfo',
              'FullCountryInfoAllCountriesResponse',
              'CountryWebService.FullCountryInfoAllCountriesResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.FullCountryInfoAllCountriesResult;
        }
    }
}